#pragma once


UENUM(BlueprintType)
enum class ECmdId : uint8 {
    HANDSHAKE = 0,
    LOGIN = 1,
    LOGIN_REPLY = 2,
    CREATE_ROOM = 100,
    LEAVE_ROOM = 101,
    JOIN_ROOM = 102,
    ROOM_INFO = 103,
    KICK_PLAYER = 104,
    SWITCH_SLOT = 105,
    START_GAME = 106,
    ADD_BOT = 107,
    NEW_PLAYER_JOIN_ROOM = 108,
    LIST_ROOM = 109,
    PLAYER_LEAVE_ROOM_NOTI = 110,
    ROOM_UPDATE_OWNER = 111,
    ROOM_UPDATE_GAME_MODE = 112,
    ROOM_UPDATE_HOST_TYPE = 113,
    SELFHOST_READY = 114, // other players can join now
    GAME_STARTED = 115,
	CHAT_IN_ROOM = 116,
    PLAYER_SESSION = 117,
	GAME_START_FAILED = 118,
	SELFHOST_START_SESSION = 119,
	NOTI_MESSAGE = 120,
	CHANGE_NAME_REQUEST = 200,
};